# Generated by Django 6.0 on 2025-12-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_document_template_data"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="docversion",
            name="doc_version_doc_id_dc212c_idx",
        ),
        migrations.AddField(
            model_name="docversion",
            name="meta",
            field=models.JSONField(
                default=dict, help_text="메타데이터 {savedFromStep, title, createdAt}"
            ),
        ),
        migrations.AddField(
            model_name="docversion",
            name="snapshot",
            field=models.JSONField(
                default=dict, help_text="5개 문서 전체 HTML 스냅샷 {1: html, ...}"
            ),
        ),
        migrations.AddField(
            model_name="docversion",
            name="trade",
            field=models.ForeignKey(
                help_text="거래 플로우",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="documents.tradeflow",
            ),
        ),
        migrations.AddIndex(
            model_name="docversion",
            index=models.Index(
                fields=["trade", "-created_at"], name="doc_version_trade_i_a1809b_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="docversion",
            name="content",
        ),
        migrations.RemoveField(
            model_name="docversion",
            name="doc",
        ),
    ]
